apiVersion: v1
kind: Pod
metadata:
  name: next-pod
  labels:
    app: next-app
spec:
  containers:
  - name: myapp-container
    imagePullPolicy: Never
    image: dockerized-nextjs
  initContainers:
  - name: init-example
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup www.google.com; do echo waiting for myservice; sleep 2; done"] 

