apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: deployment-secret-configmap
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: defaultconfig
          - secretRef:
              name: minisecret
