apiVersion: v1
kind: Service
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  selector:
    app: example
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
