apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold-express-example
build:
  artifacts:
  - image: example
    docker:
      network: bridge
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
